# Generated by Django 5.0.2 on 2024-03-30 17:40

import core.application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0004_applicationclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationclient',
            name='client_id',
            field=models.CharField(default=core.application.models.generate_client_id, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
