# Generated by Django 5.0.2 on 2024-03-30 17:43

import core.application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0005_alter_applicationclient_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationclient',
            name='client_secret',
            field=models.CharField(default=core.application.models.generate_client_secret, max_length=100),
        ),
    ]
