# Generated by Django 5.0.2 on 2024-03-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0006_alter_applicationclient_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationclient',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
