# Generated by Django 5.0.1 on 2024-01-12 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='implicit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
