# Generated by Django 5.0.1 on 2024-01-12 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_implicit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='implicit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
