# Generated by Django 5.0.2 on 2024-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0010_alter_usersettings_options_alter_usersettings_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='timezone',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Femal'), ('other', 'Other')], default='other'),
        ),
    ]
